package common

var (
	PriceCsvDataHeaders = []string{
		"DATE",
		"WILAYAH",
		"KOMODITAS",
		"PRICE",
	}

	PriceColumns = map[string]string{}

	AbjadList = []string{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"}

	BulanIndonesiaFromEnglish = map[string]string{
		"january":   "Januari",
		"february":  "Februari",
		"march":     "Maret",
		"april":     "April",
		"may":       "Mei",
		"june":      "Juni",
		"july":      "Juli",
		"august":    "Agustus",
		"september": "September",
		"october":   "Oktober",
		"november":  "November",
		"december":  "Desember",
	}

	BulanIndonesiaFromEnglishShortName = map[string]string{
		"jan": "Januari",
		"feb": "Februari",
		"mar": "Maret",
		"apr": "April",
		"may": "Mei",
		"jun": "Juni",
		"jul": "Juli",
		"aug": "Agustus",
		"sep": "September",
		"oct": "Oktober",
		"nov": "November",
		"dec": "Desember",
	}

	BulanIndonesiaFromNumber = map[string]string{
		"01": "Januari",
		"02": "Februari",
		"03": "Maret",
		"04": "April",
		"05": "Mei",
		"06": "Juni",
		"07": "Juli",
		"08": "Agustus",
		"09": "September",
		"10": "Oktober",
		"11": "November",
		"12": "Desember",
	}
)

const (
	DATETIME_FORMAT   = "2006-01-02 15:04:05"
	MODUL_TYPE_PRICE  = "PRICE"
	MODUL_TYPE_NERACA = "NERACA"

	ASSETS_TYPE_DIRECTORY      = "DIRECTORY"
	ASSETS_TYPE_PUBLIC_STORAGE = "PUBLIC_STORAGE"

	ERROR_MSG_DATA_IS_NOT_FOUND = "Data is not found!"
	ERROR_MSG_DATA_IS_EMPTY     = "Data is not empty!"

	PRICE_COMPARE_PROVINCE_MAP  = `{"status":200,"message":"Success","data":{"summary":{"higher":4,"same":16,"lower":4},"priceLevel":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar"},"commodity":{"id":1,"name":"Beras"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"higher"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo"},"commodity":{"id":1,"name":"Beras"},"price":15000,"priceRupiahFormat":"Rp 15.000","tier":"same"},{"id":6269,"clientId":1,"city":{"id":7372,"name":"Kota Parepare"},"commodity":{"id":1,"name":"Beras"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"lower"}],"priceTier":{"higher":{"title":"Lebih Tinggi","priceMin":11550,"priceMax":12240,"color":"#FF6711"},"same":{"title":"Sama","priceMin":12241,"priceMax":12930,"color":"#32D583"},"lower":{"title":"Lebih Rendah","priceMin":12931,"priceMax":13620,"color":"#05603A"}},"priceTierCode":["higher","same","lower"]}}`
	PRICE_COMPARE_PROVINCE_LIST = `{"status":200,"message":"Success","data":{"commodity":{"id":1,"name":"Beras"},"provincePrice":{"id":6148,"clientId":1,"province":{"id":7373,"name":"Provinsi Sulawesi Selatan","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000"},"priceCity":[{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000","priceDiff":50,"priceDiffFormat":"Rp 50"},{"id":6269,"clientId":1,"city":{"id":7372,"name":"Kota Parepare","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":11550,"priceRupiahFormat":"Rp 11.550","priceDiff":50,"priceDiffFormat":"Rp 50"}]}}`
	PRICE_COMMODITY             = `{"status":200,"message":"Success","data":{"commodity":{"id":1,"name":"Beras"},"cityPrice":[{"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"priceDiff":50,"priceDiffFormat":"Rp 50","price":15100,"priceRupiahFormat":"Rp 15100"}]}}`
	PRICE_COMPARE_NATIONAL_MAP  = `{"status":200,"message":"Success","data":{"commodity":{"id":1,"name":"Beras"},"summary":{"higher":4,"same":16,"lower":4},"provincePrice":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"higher"},"priceLevel":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"higher"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo"},"price":15000,"priceRupiahFormat":"Rp 15.000","tier":"same"},{"id":6269,"clientId":1,"city":{"id":7372,"name":"Kota Parepare"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"lower"}],"priceTier":{"higher":{"title":"Lebih Tinggi","priceMin":11550,"priceMax":12240,"color":"#FF6711"},"same":{"title":"Sama","priceMin":12241,"priceMax":12930,"color":"#32D583"},"lower":{"title":"Lebih Rendah","priceMin":12931,"priceMax":13620,"color":"#05603A"}},"priceTierCode":["higher","same","lower"]}}`
	PRICE_COMPARE_NATIONAL_LIST = `{"status":200,"message":"Success","data":{"commodity":{"id":1,"name":"Beras"},"nationalPrice":{"id":6148,"clientId":1,"country":{"id":7373,"name":"Indonesia","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000"},"provincePrice":{"id":6148,"clientId":1,"province":{"id":7373,"name":"Provinsi Sulawesi Selatan","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000","priceDiff":50,"priceDiffFormat":"Rp 50"},"cityPrice":[{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000","priceDiff":50,"priceDiffFormat":"Rp 50"},{"id":6269,"clientId":1,"city":{"id":7372,"name":"Kota Parepare","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":11550,"priceRupiahFormat":"Rp 11.550","priceDiff":50,"priceDiffFormat":"Rp 50"}]}}`
	PRICE_MTM_MAP               = `{"status":200,"message":"Success","data":{"summary":{"higher":4,"same":16,"lower":4},"provincePrice":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"higher"},"priceLevel":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar"},"commodity":{"id":1,"name":"Beras"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"higher"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo"},"commodity":{"id":1,"name":"Beras"},"price":15000,"priceRupiahFormat":"Rp 15.000","tier":"same"},{"id":6269,"clientId":1,"city":{"id":7372,"name":"Kota Parepare"},"commodity":{"id":1,"name":"Beras"},"price":11550,"priceRupiahFormat":"Rp 11.550","tier":"lower"}],"priceTier":{"higher":{"title":"Meningkat","priceMin":11550,"priceMax":12240,"color":"#FF6711"},"same":{"title":"Stabil","priceMin":12241,"priceMax":12930,"color":"#32D583"},"lower":{"title":"Menurun","priceMin":12931,"priceMax":13620,"color":"#05603A"}},"priceTierCode":["higher","same","lower"]}}`
	PRICE_MTM_LIST              = `{"status":200,"message":"Success","data":{"commodity":{"id":1,"name":"Beras"},"provincePrice":{"id":6148,"clientId":1,"province":{"id":7373,"name":"Provinsi Sulawesi Selatan","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000","priceDiffPercentage":0.75},"priceCity":[{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":15000,"priceRupiahFormat":"Rp 15.000","priceDiff":50,"priceDiffFormat":"Rp 50","priceDiffPercentage":0.75},{"id":6269,"clientId":1,"city":{"id":7372,"name":"Kota Parepare","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"price":11550,"priceRupiahFormat":"Rp 11.550","priceDiff":50,"priceDiffFormat":"Rp 50","priceDiffPercentage":0.75}]}}`

	NERACA_STOCK_AKHIR_BY_COMMODITY_MAP              = `{"status":200,"message":"Success","data":{"unit":"ton","commodity":{"id":1,"name":"Beras"},"summary":{"defisit":2,"rentan":3,"waspada":1,"aman":18},"provinceStock":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan"},"stock":920,"tier":"aman"},"cityStock":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":920,"tier":"aman"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kabupaten Wajo","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":920,"tier":"waspada"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kabupaten Bone","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":-100,"tier":"defisit"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":null,"tier":null}],"stockTier":{"defisit":{"title":"Defisit","start":null,"end":0,"color":"#B11016","unit":"percentage","backgroundColor":"FEF3F2"},"rentan":{"title":"Rentan","start":0,"end":46,"color":"#FF6711","unit":"percentage","backgroundColor":"FEEFC6"},"waspada":{"title":"Waspada","start":47,"end":80,"color":"#E4B701","unit":"percentage","backgroundColor":"FFFAEB"},"aman":{"title":"Aman","start":81,"end":100,"color":"#05603A","unit":"percentage","backgroundColor":"D1FADF"}},"stockTierCode":["defisit","rentan","waspada","aman"]}}`
	NERACA_STOCK_AKHIR_BY_COMMODITY_LIST             = `{"status":200,"message":"Success","data":{"unit":"ton","commodity":{"id":1,"name":"Beras"},"provinceStock":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":920,"tier":"aman"},"cityStock":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"commodity":null,"stock":920,"tier":"aman"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"commodity":{"id":1,"name":"Beras"},"stock":920,"tier":"aman"}],"stockTier":{"defisit":{"title":"Defisit","start":null,"end":0,"color":"#B11016","unit":"percentage","backgroundColor":"FEF3F2"},"rentan":{"title":"Rentan","start":0,"end":46,"color":"#FF6711","unit":"percentage","backgroundColor":"FEEFC6"},"waspada":{"title":"Waspada","start":47,"end":80,"color":"#E4B701","unit":"percentage","backgroundColor":"FFFAEB"},"aman":{"title":"Aman","start":81,"end":100,"color":"#05603A","unit":"percentage","backgroundColor":"D1FADF"}}}}`
	NERACA_LOCATION_SUMMARY                          = `{"status":200,"message":"Success","data":{"unit":"ton","commodity":{"id":1,"name":"Beras"},"cityStock":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":920,"tier":"aman"}],"stockTier":{"defisit":{"title":"Defisit","start":null,"end":0,"color":"#B11016","unit":"percentage","backgroundColor":"FEF3F2"},"rentan":{"title":"Rentan","start":0,"end":46,"color":"#FF6711","unit":"percentage","backgroundColor":"FEEFC6"},"waspada":{"title":"Waspada","start":47,"end":80,"color":"#E4B701","unit":"percentage","backgroundColor":"FFFAEB"},"aman":{"title":"Aman","start":81,"end":100,"color":"#05603A","unit":"percentage","backgroundColor":"D1FADF"}}}}`
	NERACA_MAP_SUMMARY                               = `{"status":200,"message":"Success","data":{"unit":"ton","commodity":{"id":1,"name":"Beras"},"city":{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":920,"tier":"aman"},"stockDiff":50,"stock":[{"date":"1 Maret 2024","stock":22,"stockFormat":"12 Ton"},{"date":"2 Maret 2024","stock":18,"stockFormat":"18 Ton"},{"date":"3 Maret 2024","stock":19,"stockFormat":"19 Ton"}],"stockTier":{"defisit":{"title":"Defisit","start":null,"end":0,"color":"#B11016","unit":"percentage","backgroundColor":"FEF3F2"},"rentan":{"title":"Rentan","start":0,"end":46,"color":"#FF6711","unit":"percentage","backgroundColor":"FEEFC6"},"waspada":{"title":"Waspada","start":47,"end":80,"color":"#E4B701","unit":"percentage","backgroundColor":"FFFAEB"},"aman":{"title":"Aman","start":81,"end":100,"color":"#05603A","unit":"percentage","backgroundColor":"D1FADF"}}}}`
	NERACA_KETERSEDIAAN_BY_COMMODITY_MAP             = `{"status":200,"message":"Success","data":{"unit":"ton","unitDiff":"percentage","commodity":{"id":1,"name":"Beras"},"summary":{"menurun":4,"stabil":16,"meningkat":4},"provinceStock":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan"},"stock":920,"stockDiff":-0.9,"tier":"menurun"},"cityStock":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":920,"stockDiff":0,"tier":"stabil"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kabupaten Wajo","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":920,"stockDiff":0.9,"tier":"waspada"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kabupaten Bone","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":-100,"stockDiff":0.9,"tier":"meningkat"}],"stockTier":{"menurun":{"title":"Menurun","color":"#FF6711"},"stabil":{"title":"Stabil","color":"#32D583"},"meningkat":{"title":"Meningkat","color":"#05603A"}},"stockTierCode":["menurun","stabil","meningkat"]}}`
	NERACA_KETERSEDIAAN_BY_COMMODITY_LIST            = `{"status":200,"message":"Success","data":{"unit":"ton","unitDiff":"percentage","commodity":{"id":1,"name":"Beras"},"provinceStock":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":920,"stockDiff":-0.9,"tier":"menurun"},"cityStock":[{"id":6027,"clientId":1,"city":{"id":7371,"name":"Kota Makassar","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":920,"stockDiff":0,"tier":"stabil"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kabupaten Wajo","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":920,"stockDiff":0.9,"tier":"waspada"},{"id":6148,"clientId":1,"city":{"id":7373,"name":"Kabupaten Bone","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stock":-100,"stockDiff":0.9,"tier":"meningkat"}],"stockTier":{"menurun":{"title":"Menurun","color":"#FF6711"},"stabil":{"title":"Stabil","color":"#32D583"},"meningkat":{"title":"Meningkat","color":"#05603A"}},"stockTierCode":["menurun","stabil","meningkat"]},"totalData":1000,"page":1,"totalPage":"10"}`
	NERACA_KETERSEDIAAN_BY_CITY_AND_COMMODITY_CHART_ = `{"status":200,"message":"Success","data":{"unit":"ton","unitDiff":"percentage","commodity":{"id":1,"name":"Beras"},"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stockDiff":8,"stock":[{"date":"15 Juni 2024","stock":12},{"date":"16 Juni 2024","stock":16},{"date":"17 Juni 2024","stock":20}]}}`
	NERACA_STOCK_AKHIR_BY_CITY_MAP                   = `{"status":200,"message":"Success","data":{"unit":"ton","city":{"id":7371,"name":"Kota Makassar","assets":{"id":7,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PAREPARE_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PAREPARE_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"summary":{"defisit":2,"rentan":3,"waspada":1,"aman":18},"provinceStock":{"id":6027,"clientId":1,"province":{"id":7371,"name":"Sulawesi Selatan"},"stock":920,"tier":"aman"},"commodityStock":[{"id":6027,"clientId":1,"commodity":{"id":1,"name":"Beras","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/commodity","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"beras.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":920,"tier":"aman"},{"id":6148,"clientId":1,"commodity":{"id":1,"name":"Beras","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":920,"tier":"waspada"},{"id":6148,"clientId":1,"commodity":{"id":1,"name":"Beras","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":-100,"tier":"defisit"},{"id":6148,"clientId":1,"commodity":{"id":1,"name":"Beras","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"}},"stock":null,"tier":null}],"stockTier":{"defisit":{"title":"Defisit","start":null,"end":0,"color":"#B11016","unit":"percentage","backgroundColor":"FEF3F2"},"rentan":{"title":"Rentan","start":0,"end":46,"color":"#FF6711","unit":"percentage","backgroundColor":"FEEFC6"},"waspada":{"title":"Waspada","start":47,"end":80,"color":"#E4B701","unit":"percentage","backgroundColor":"FFFAEB"},"aman":{"title":"Aman","start":81,"end":100,"color":"#05603A","unit":"percentage","backgroundColor":"D1FADF"}},"stockTierCode":["defisit","rentan","waspada","aman"]}}`
	NERACA_STOCK_AKHIR_BY_CITY_AND_COMMODITY         = `{"status":200,"message":"Success","data":{"unit":"ton","unitDiff":"percentage","commodity":{"id":1,"name":"Beras"},"city":{"id":7373,"name":"Kota Palopo","assets":{"id":6,"assetsType":"IMAGE","assetsLocation":"resources/city-logo","assetsLocationType":"DIRECTORY","assetsMediaType":"image/png","assetsExt":".png","assetsName":"KOTA_PALOPO_LOGO.png","assetsUrl":"https://project.bi.sentech.id/api/v1/stg/assets?assets_location=../resources/city-logo/KOTA_PALOPO_LOGO.png"},"createdAt":null,"updatedAt":null,"deletedAt":null},"stockDiff":8,"stock":[{"period":"Januari 2024","neraca":-935,"ketersediaan":2996,"kebutuhan":2062,"tier":"default"},{"period":"Februari 2024","neraca":1320,"ketersediaan":3428,"kebutuhan":2110,"tier":"aman"},{"period":"Maret 2024","neraca":748,"ketersediaan":2777,"kebutuhan":2029,"tier":"waspada"}],"stockTier":{"defisit":{"title":"Defisit","color":"#B11016","unit":"percentage","backgroundColor":"FEF3F2"},"rentan":{"title":"Rentan","color":"#FF6711","unit":"percentage","backgroundColor":"FEEFC6"},"waspada":{"title":"Waspada","color":"#E4B701","unit":"percentage","backgroundColor":"FFFAEB"},"aman":{"title":"Aman","color":"#05603A","unit":"percentage","backgroundColor":"D1FADF"}}}}`
)

type ModuleReportType struct {
	PriceNational  bool
	PriceProvince  bool
	PriceCity      bool
	NeracaNational bool
	NeracaProvince bool
	NeracaCity     bool
}
type ModuleType struct {
	Price  bool
	Neraca bool
}
