
export const cities = [
  "Kepulauan Selayar",
  "Bulukumba",
  "Bantaeng",
  "Jeneponto",
  "Takalar",
  "Gowa",
  "Sinjai",
  "Maros",
  "Pangkajene Dan Kepulauan",
  "Barru",
  "Bone",
  "Soppeng",
  "Wajo",
  "Sidenreng Rappang",
  "Pinrang",
  "Enrekang",
  "Luwu",
  "Tana Toraja",
  "Luwu Utara",
  "Luwu Timur",
  "Toraja Utara",
  "Makassar",
  "Parepare",
  "Palopo",
];